//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BitsionProyect.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compania
    {
        public Compania()
        {
            this.Documentoes = new HashSet<Documento>();
        }
    
        public int IdCompania { get; set; }
        public string RazonSocial { get; set; }
        public string Nit { get; set; }
        public string ResponseUrl { get; set; }
        public string Activo { get; set; }
        public string LogueoAutomatico { get; set; }
    
        public virtual ICollection<Documento> Documentoes { get; set; }
    }
}
