//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BitsionProyect.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentoDetalle
    {
        public int IdDocumentoDetalle { get; set; }
        public int IdDocumento { get; set; }
        public string Codigo { get; set; }
        public string Cantidad { get; set; }
        public string Descripcion { get; set; }
        public string Importe { get; set; }
        public string Impuesto { get; set; }
        public string Subtotal { get; set; }
    
        public virtual Documento Documento { get; set; }
    }
}
