//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BitsionProyect.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Documento
    {
        public Documento()
        {
            this.DocumentoDetalles = new HashSet<DocumentoDetalle>();
            this.LOG_Post = new HashSet<LOG_Post>();
            this.LOG_Proceso = new HashSet<LOG_Proceso>();
            this.LOG_Sincronizacion = new HashSet<LOG_Sincronizacion>();
        }
    
        public int IdDocumento { get; set; }
        public int IdCompania { get; set; }
        public int IdPersona { get; set; }
        public string NumeroDocumento { get; set; }
        public string NumeroDocumentoOrigen { get; set; }
        public string CodigoBarra { get; set; }
        public string FechaDocumento { get; set; }
        public string FechaVencimiento { get; set; }
        public string Importe { get; set; }
        public string Impuesto { get; set; }
        public string Subtotal { get; set; }
        public string Rubro { get; set; }
        public string Moneda { get; set; }
        public string IdEstadoCobro { get; set; }
    
        public virtual Compania Compania { get; set; }
        public virtual Persona Persona { get; set; }
        public virtual ICollection<DocumentoDetalle> DocumentoDetalles { get; set; }
        public virtual ICollection<LOG_Post> LOG_Post { get; set; }
        public virtual ICollection<LOG_Proceso> LOG_Proceso { get; set; }
        public virtual ICollection<LOG_Sincronizacion> LOG_Sincronizacion { get; set; }
    }
}
