//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BitsionProyect.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOG_Sincronizacion
    {
        public int IdSincronizacion { get; set; }
        public int IdDocumento { get; set; }
        public string Fecha { get; set; }
        public string Resultado { get; set; }
        public string Mensaje { get; set; }
        public string StackTrace { get; set; }
    
        public virtual Documento Documento { get; set; }
    }
}
