//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BitsionProyect.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class iRecaudo_COEEntities : DbContext
    {
        public iRecaudo_COEEntities()
            : base("name=iRecaudo_COEEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Compania> Companias { get; set; }
        public DbSet<Documento> Documentoes { get; set; }
        public DbSet<DocumentoDetalle> DocumentoDetalles { get; set; }
        public DbSet<LOG_Post> LOG_Post { get; set; }
        public DbSet<LOG_Proceso> LOG_Proceso { get; set; }
        public DbSet<LOG_Sincronizacion> LOG_Sincronizacion { get; set; }
        public DbSet<Persona> Personas { get; set; }
    }
}
